### ISSUE TITLE
[feature] Is it possible to publish geograph on conda-forge?

### ISSUE THREAD

**Issue by CWen001** [ai4er-cdt/geograph#68]
Hi there. Thank you very much for this timely package! I have used it for a while and enjoy it very much along with `pylandstats`. 

I was wondering if it is possible to publish `geograph` on conda-forge? Currently many users like to use anaconda to manage packages and environments, especially when dealing with spatial packages like `geopandas`, or 'fiona'. So it would be nice if `geograph` can be also available on that.

**Comment by Croydon-Brixton** [comment]
Hi and thanks for your interest in `geograph`! 

Great idea, we are happy to publish it on conda-forge. I will work on it.

**Comment by herbiebradley** [comment]
Done! Just do `conda install -c conda-forge geograph` 🎉 It takes a few minutes to resolve because it's >100 packages in a fresh environment.

Currently it only works with `python=3.8` because some of the dependencies can't be resolved for `python=3.9`. I will update the `geograph` conda-forge yaml recipe to force this.

Links:
- https://anaconda.org/conda-forge/geograph
- https://github.com/conda-forge/geograph-feedstock

**Comment by herbiebradley** [comment]
Done! Just do conda install -c conda-forge geograph 🎉 It takes a few minutes to resolve because it's >100 packages in a fresh environment.

Currently it only works with python=3.8 because some of the dependencies can't be resolved for python=3.9. I will update the geograph conda-forge yaml recipe to force this.

Links:

https://anaconda.org/conda-forge/geograph
https://github.com/conda-forge/geograph-feedstock
